import { AirportDetails } from "./select";

export const mockFlights = [
  {
    id: "1",
    name: "Flight JFK-LAX",
    source: "John F. Kennedy International Airport",
    sourceCode: "JFK",
    destination: "Los Angeles International Airport",
    destinationCode: "LAX",
    returnSource: "LAX",
    returnDestination: "JFK",
    returnDeparture: "14:00:00",
    returnArrival: "21:30:00",
    departure: "10:00:00",
    arrival: "13:30:00",
    travelTime: "5h 30m",
    numberOfStops: 0,
    fare: 350,
  },
  {
    id: "13",
    name: "Flight JFK-LAX",
    source: "John F. Kennedy International Airport",
    sourceCode: "JFK",
    destination: "Los Angeles International Airport",
    destinationCode: "LAX",
    returnSource: "LAX",
    returnDestination: "JFK",
    returnDeparture: "14:00:00",
    returnArrival: "21:30:00",
    departure: "10:00:00",
    arrival: "13:30:00",
    travelTime: "5h 30m",
    returnTravelTime: "7h 30min",
    numberOfStops: 0,
    fare: 350,
  },
  {
    id: "143",
    name: "Flight JFK-LAX",
    source: "John F. Kennedy International Airport",
    sourceCode: "JFK",
    destination: "Los Angeles International Airport",
    destinationCode: "LAX",
    returnSource: "LAX",
    returnDestination: "JFK",
    returnDeparture: "14:00:00",
    returnArrival: "21:30:00",
    departure: "10:00:00",
    arrival: "13:30:00",
    travelTime: "5h 30m",
    numberOfStops: 0,
    fare: 350,
  },
  {
    id: "2",
    name: "Flight SFO-SEA",
    source: "San Francisco International Airport",
    sourceCode: "SFO",
    destination: "Seattle-Tacoma International Airport",
    destinationCode: "SEA",
    returnSource: "SEA",
    returnDestination: "SFO",
    returnDeparture: "15:00:00",
    returnArrival: "16:30:00",
    departure: "12:00:00",
    arrival: "13:30:00",
    travelTime: "2h 30m",
    numberOfStops: 0,
    fare: 250,
  },
  {
    id: "3",
    name: "Flight ORD-DEN",
    source: "O'Hare International Airport",
    sourceCode: "ORD",
    destination: "Denver International Airport",
    destinationCode: "DEN",
    returnSource: "DEN",
    returnDestination: "ORD",
    returnDeparture: "17:00:00",
    returnArrival: "20:00:00",
    departure: "14:00:00",
    arrival: "15:30:00",
    travelTime: "2h 30m",
    numberOfStops: 0,
    fare: 200,
  },
  {
    id: "4",
    name: "Flight ATL-MIA",
    source: "Hartsfield-Jackson Atlanta International Airport",
    sourceCode: "ATL",
    destination: "Miami International Airport",
    destinationCode: "MIA",
    returnSource: "MIA",
    returnDestination: "ATL",
    returnDeparture: "19:00:00",
    returnArrival: "20:30:00",
    departure: "16:00:00",
    arrival: "17:30:00",
    travelTime: "1h 30m",
    numberOfStops: 0,
    fare: 150,
  },
  {
    id: "5",
    name: "Flight LAX-NY",
    source: "Los Angeles International Airport",
    sourceCode: "LAX",
    destination: "Newark Liberty International Airport",
    destinationCode: "EWR",
    returnSource: "EWR",
    returnDestination: "LAX",
    returnDeparture: "18:00:00",
    returnArrival: "21:00:00",
    departure: "15:00:00",
    arrival: "23:00:00",
    travelTime: "5h 00m",
    numberOfStops: 0,
    fare: 400,
  },
  {
    id: "6",
    name: "Flight BOS-ORD",
    source: "Logan International Airport",
    sourceCode: "BOS",
    destination: "O'Hare International Airport",
    destinationCode: "ORD",
    returnSource: "ORD",
    returnDestination: "BOS",
    returnDeparture: "16:30:00",
    returnArrival: "18:00:00",
    departure: "13:30:00",
    arrival: "14:30:00",
    travelTime: "2h 00m",
    numberOfStops: 0,
    fare: 180,
  },
];

export const mockAirports: AirportDetails[] = [
  {
    id: "1",
    name: "John F. Kennedy International Airport",
    code: "JFK",
  },
  {
    id: "2",
    name: "Heathrow Airport",
    code: "LHR",
  },
  {
    id: "3",
    name: "Los Angeles International Airport",
    code: "LAX",
  },
  {
    id: "4",
    name: "Dubai International Airport",
    code: "DXB",
  },
  {
    id: "5",
    name: "Changi Airport",
    code: "SIN",
  },
  {
    id: "6",
    name: "Indira Gandhi International Airport",
    code: "DEL",
  },
  {
    id: "7",
    name: "Charles de Gaulle Airport",
    code: "CDG",
  },
  {
    id: "8",
    name: "Sydney Kingsford Smith Airport",
    code: "SYD",
  },
  {
    id: "9",
    name: "Toronto Pearson International Airport",
    code: "YYZ",
  },
  {
    id: "10",
    name: "San Francisco International Airport",
    code: "SFO",
  },
];
